services:
    problem:
        database:
            host: problem-db
            port: 27001
            name: problem
    submission:
        database:
            host: submission-db
            port: 27002
            name: submission
    status:
        queue:
            host: status-queue
            port: 27003
    code-runner:
        container-files: /tmp/code-runner
        languages:
            PROGRAMMING_LANGUAGE_PYTHON:
                display-name: 'Python 3.11'
                docker-image: 'python:3.11.4-slim'
                main-file: 'main.py'
                run-command: python3 {FILE} {ARGS}
            PROGRAMMING_LANGUAGE_JAVA:
                display-name: 'Java 21'
                docker-image: 'amazoncorretto:21.0.1'
                main-file: 'Main.java'
                run-command: java /tmp/code-runner/Main.java
            PROGRAMMING_LANGUAGE_JAVASCRIPT:
                display-name: 'JavaScript'
                docker-image: 'node:lts-slim'
                main-file: 'main.js'
                run-command: node /tmp/code-runner/main.js
            PROGRAMMING_LANGUAGE_C:
                display-name: 'C'
                docker-image: 'gcc:13.2.0'
                main-file: 'main.c'
                run-command: gcc -o main /tmp/code-runner/main.c && ./main
            PROGRAMMING_LANGUAGE_PROLOG:
                display-name: 'Prolog 9.2.1'
                docker-image: 'swipl:9.2.1'
                main-file: 'main.pl'
                run-command: swipl -g "consult('{FILE}'), {ARGS}, nl, halt." -t 'halt.'