apiVersion: v1
data:
  submissiondb-root-username: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: submissiondb-root-username
  name: submissiondb-root-username
type: Opaque
