apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert --file docker-test.yml -c -o helm
        kompose.version: 1.32.0 (HEAD)
    creationTimestamp: null
    labels:
        io.kompose.service: problem
    name: problem
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: problem
    strategy: {}
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert --file docker-test.yml -c -o helm
                kompose.version: 1.32.0 (HEAD)
            creationTimestamp: null
            labels:
                io.kompose.network/codelabmesh: 'true'
                io.kompose.service: problem
        spec:
            containers:
                - args:
                      - python3
                      - /service/service.py
                  env:
                      - name: CODE_RUNNER_SERVICE_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: CODE_RUNNER_SERVICE_PORT
                                name: env
                      - name: DIGITAL_REGISTRY
                        valueFrom:
                            configMapKeyRef:
                                key: DIGITAL_REGISTRY
                                name: env
                      - name: DIGITAL_REGISTRY_ACCESS_TOKEN
                        valueFrom:
                            configMapKeyRef:
                                key: DIGITAL_REGISTRY_ACCESS_TOKEN
                                name: env
                      - name: ENVIRONMENT
                        valueFrom:
                            configMapKeyRef:
                                key: ENVIRONMENT
                                name: env
                      - name: ENVOY_EDGE_GATEWAY_ADMIN_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: ENVOY_EDGE_GATEWAY_ADMIN_PORT
                                name: env
                      - name: ENVOY_EDGE_GATEWAY_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: ENVOY_EDGE_GATEWAY_PORT
                                name: env
                      - name: FRONTEND_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: FRONTEND_PORT
                                name: env
                      - name: GOOGLE_OAUTH_CLIENT_ID
                        valueFrom:
                            configMapKeyRef:
                                key: GOOGLE_OAUTH_CLIENT_ID
                                name: env
                      - name: GOOGLE_OAUTH_CLIENT_SECRET
                        valueFrom:
                            configMapKeyRef:
                                key: GOOGLE_OAUTH_CLIENT_SECRET
                                name: env
                      - name: GRAFANA_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: GRAFANA_PORT
                                name: env
                      - name: HOST
                        valueFrom:
                            configMapKeyRef:
                                key: HOST
                                name: env
                      - name: NEXTAUTH_SECRET
                        valueFrom:
                            configMapKeyRef:
                                key: NEXTAUTH_SECRET
                                name: env
                      - name: NEXTAUTH_URL
                        valueFrom:
                            configMapKeyRef:
                                key: NEXTAUTH_URL
                                name: env
                      - name: NEXT_PUBLIC_FRONTEND_URL
                        valueFrom:
                            configMapKeyRef:
                                key: NEXT_PUBLIC_FRONTEND_URL
                                name: env
                      - name: PROBLEM_DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: PROBLEM_DB_PORT
                                name: env
                      - name: PROBLEM_SERVICE_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: PROBLEM_SERVICE_PORT
                                name: env
                      - name: PROMETHEUS_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: PROMETHEUS_PORT
                                name: env
                      - name: STATUS_QUEUE_MANAGEMENT_PLUGIN_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: STATUS_QUEUE_MANAGEMENT_PLUGIN_PORT
                                name: env
                      - name: STATUS_QUEUE_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: STATUS_QUEUE_PORT
                                name: env
                      - name: STATUS_SERVICE_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: STATUS_SERVICE_PORT
                                name: env
                      - name: SUBMISSION_DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: SUBMISSION_DB_PORT
                                name: env
                      - name: SUBMISSION_SERVICE_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: SUBMISSION_SERVICE_PORT
                                name: env
                      - name: TEST_FILTER
                        valueFrom:
                            configMapKeyRef:
                                key: TEST_FILTER
                                name: env
                      - name: USER_DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: USER_DB_PORT
                                name: env
                  image: registry.digitalocean.com/codelab/codelab:problem
                  name: problem
                  resources: {}
                  volumeMounts:
                      - mountPath: /service-config
                        name: service-config
                        subPath: service-config
                      - mountPath: /run/secrets/problemdb-root-username
                        name: problemdb-root-username
                      - mountPath: /run/secrets/problemdb-root-password
                        name: problemdb-root-password
            restartPolicy: Always
            volumes:
                - configMap:
                      items:
                          - key: config.yaml
                            path: service-config
                      name: service-config
                  name: service-config
                - name: problemdb-root-username
                  secret:
                      items:
                          - key: problemdb-root-username
                            path: problemdb-root-username
                      secretName: problemdb-root-username
                - name: problemdb-root-password
                  secret:
                      items:
                          - key: problemdb-root-password
                            path: problemdb-root-password
                      secretName: problemdb-root-password
status: {}
