apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.gateway.name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.gateway.host }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: codelab-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "{{ .Values.gateway.host }}"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: "/protobufs.services.v1.ProblemService"
    route:
    - destination:
        host: {{ .Values.problemService.name }}
        port:
          number: {{ .Values.problemService.port }}
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ .Values.frontend.name }}
        port:
          number: 80