apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | quote }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name | quote }}
  ports:
    - protocol: TCP
      port: 19990
      targetPort: 19990
