apiVersion: v2
name: CodeLAB
description: CodeLAB Application
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: problem
    version: 1.0.0
    repository: file://charts/problem