apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
type: Opaque
data:
  mongodb-username: {{ .Values.secret.user }}
  mongodb-password: {{ .Values.secret.pass }}
  mongodb-root-username: {{ .Values.secret.root_user }}
  mongodb-root-password: {{ .Values.secret.root_pass }}