apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
type: Opaque
data:
  problemdb-username: Y29kZWxhYg==
  problemdb-password: Y29kZWxhYg==
  problemdb-root-username: cm9vdA==
  problemdb-root-password: cGFzc3dvcmQ=